name: Docusarurus Version Compatibility Test

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request: {}
  workflow_dispatch: {}

jobs:
  compatibility-test:
    runs-on: ubuntu-latest
    name: Docusaurus @${{ matrix.docusaurus-version }}

    strategy:
      matrix:
        docusaurus-version: ['3.0.0']

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - uses: scalvert/docusaurus-version-compatibility@v1
        with:
          version: ${{ matrix.docusaurus-version }}
      - run: yarn --no-immutable
      - run: yarn test
