name: Docusarurus Version Compatibility Test

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: Install dependencies
        run: yarn
      - name: Run version compatibility test
        uses: docusaurus-version-compatibility@master
